[tool.poetry]
name = "google-photos-organizer"
version = "0.1.0"
description = ""
authors = ["jerome provensal <jeromegit@provensal.com>"]
readme = "README.md"
packages = [{include = "google_photos_organizer"}]

[tool.poetry.dependencies]
python = "^3.9"
google-api-python-client = "^2.108.0"
google-auth-oauthlib = "^1.1.0"
google-auth-httplib2 = "^0.1.1"
pillow = "^10.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
